/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author JayJomJohn
 */
public class ChangePassword extends javax.swing.JFrame {

public static String usernameGetter, passwordGetter;
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    public ChangePassword() {
        initComponents();
        conn=JavaConnector.ConnectDb();
        Reset();
        SetIcon();
    }
    
//DISPLAY ICON
private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/IconA/icons8_airport_35px.png")));
    }       

 private void Reset() {
        txtCurrentPassword.setText("");
        txtNewPassword.setText("");
        txtConfirmNewPassword.setText("");
        chckbox_ShowPassword1.setSelected(false);
        chckbox_ShowPassword2.setSelected(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCurrentPassword = new javax.swing.JLabel();
        txtCurrentPassword = new javax.swing.JPasswordField();
        chckbox_ShowPassword1 = new javax.swing.JCheckBox();
        lblNewPassword = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        lblConfirmNewPassword = new javax.swing.JLabel();
        txtConfirmNewPassword = new javax.swing.JPasswordField();
        chckbox_ShowPassword2 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        btnChangePassword = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_userid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_secretcode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(520, 516));
        setPreferredSize(new java.awt.Dimension(520, 516));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCurrentPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCurrentPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblCurrentPassword.setText("CURRENT PASSWORD");
        jPanel2.add(lblCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 132, -1, 36));

        txtCurrentPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCurrentPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtCurrentPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCurrentPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(211, 84, 0)));
        txtCurrentPassword.setCaretColor(new java.awt.Color(211, 84, 0));
        txtCurrentPassword.setOpaque(false);
        txtCurrentPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCurrentPasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurrentPasswordKeyTyped(evt);
            }
        });
        jPanel2.add(txtCurrentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 132, 240, 36));

        chckbox_ShowPassword1.setBackground(new java.awt.Color(51, 0, 102));
        chckbox_ShowPassword1.setForeground(new java.awt.Color(255, 255, 255));
        chckbox_ShowPassword1.setText("SHOW PASSWORD");
        chckbox_ShowPassword1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chckbox_ShowPassword1.setOpaque(false);
        chckbox_ShowPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbox_ShowPassword1ActionPerformed(evt);
            }
        });
        jPanel2.add(chckbox_ShowPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        lblNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblNewPassword.setText("NEW PASSWORD");
        jPanel2.add(lblNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 216, 180, 36));

        txtNewPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtNewPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNewPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(211, 84, 0)));
        txtNewPassword.setCaretColor(new java.awt.Color(211, 84, 0));
        txtNewPassword.setOpaque(false);
        txtNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewPasswordKeyTyped(evt);
            }
        });
        jPanel2.add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 216, 240, 36));

        lblConfirmNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblConfirmNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmNewPassword.setText("CONFIRM NEW PASSWORD");
        jPanel2.add(lblConfirmNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 264, 432, 36));

        txtConfirmNewPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtConfirmNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmNewPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConfirmNewPassword.setBorder(null);
        txtConfirmNewPassword.setCaretColor(new java.awt.Color(211, 84, 0));
        txtConfirmNewPassword.setOpaque(false);
        txtConfirmNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConfirmNewPasswordKeyTyped(evt);
            }
        });
        jPanel2.add(txtConfirmNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 300, 432, 36));

        chckbox_ShowPassword2.setBackground(new java.awt.Color(51, 0, 102));
        chckbox_ShowPassword2.setForeground(new java.awt.Color(255, 255, 255));
        chckbox_ShowPassword2.setText("SHOW PASSWORD");
        chckbox_ShowPassword2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chckbox_ShowPassword2.setOpaque(false);
        chckbox_ShowPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbox_ShowPassword2ActionPerformed(evt);
            }
        });
        jPanel2.add(chckbox_ShowPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 348, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 336, 432, 12));

        btnChangePassword.setBackground(new java.awt.Color(0, 51, 102));
        btnChangePassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconA/icons8_re_enter_pincode_35px.png"))); // NOI18N
        btnChangePassword.setText("CHANGE");
        btnChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePassword.setIconTextGap(10);
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        jPanel2.add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 384, 180, 48));

        btnBack.setBackground(new java.awt.Color(211, 84, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconA/icons8_back_35px.png"))); // NOI18N
        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setIconTextGap(10);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 384, 180, 48));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 36, 180, 36));

        txt_userid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_userid.setForeground(new java.awt.Color(255, 255, 255));
        txt_userid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_userid.setCaretColor(new java.awt.Color(211, 84, 0));
        txt_userid.setOpaque(false);
        txt_userid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_useridKeyReleased(evt);
            }
        });
        jPanel2.add(txt_userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 36, 240, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SECRET CODE:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 84, 180, 36));

        txt_secretcode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_secretcode.setForeground(new java.awt.Color(255, 255, 255));
        txt_secretcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_secretcode.setCaretColor(new java.awt.Color(211, 84, 0));
        txt_secretcode.setOpaque(false);
        jPanel2.add(txt_secretcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 84, 240, 36));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 516, 516));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCurrentPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurrentPasswordKeyReleased
        if (!txtCurrentPassword.getText().equals("")) {
            btnBack.setText("CANCEL");
        } else {
            btnBack.setText("BACK");
        }
    }//GEN-LAST:event_txtCurrentPasswordKeyReleased

    private void txtCurrentPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurrentPasswordKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtCurrentPassword.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCurrentPasswordKeyTyped

    private void chckbox_ShowPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbox_ShowPassword1ActionPerformed
        if (chckbox_ShowPassword1.isSelected()) {
            txtCurrentPassword.setEchoChar((char) 0);
        } else {
            txtCurrentPassword.setEchoChar('*');
        }
        this.lblCurrentPassword.requestFocus();
    }//GEN-LAST:event_chckbox_ShowPassword1ActionPerformed

    private void txtNewPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPasswordKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtNewPassword.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNewPasswordKeyTyped

    private void txtConfirmNewPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmNewPasswordKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtConfirmNewPassword.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_txtConfirmNewPasswordKeyTyped

    private void chckbox_ShowPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbox_ShowPassword2ActionPerformed
        if (chckbox_ShowPassword2.isSelected()) {
            txtNewPassword.setEchoChar((char) 0);
            txtConfirmNewPassword.setEchoChar((char) 0);
        } else {
            txtNewPassword.setEchoChar('*');
            txtConfirmNewPassword.setEchoChar('*');
        }
        this.lblCurrentPassword.requestFocus();
    }//GEN-LAST:event_chckbox_ShowPassword2ActionPerformed

//    private void Reading() {
//        if (!txtNewPassword.getText().equals(txtConfirmNewPassword.getText())) {
//            JOptionPane.showMessageDialog(this, "Your New Password and Confirm New Password are not the same !", "ATTENTION", JOptionPane.ERROR_MESSAGE);
//        } else if (txtCurrentPassword.getText().equals(txtConfirmNewPassword.getText())) {
//            JOptionPane.showMessageDialog(this, "Your Password is current used !", "ATTENTION", JOptionPane.ERROR_MESSAGE);
//        } else {
//            Updating();
//        }
//    }
    
//    private void Updating() {
//        try {
//            String sql = "UPDATE tbl_user set Password=? WHERE Userid=?";
//            pst = conn.prepareStatement(sql);
//            pst.setString(1, txtConfirmNewPassword.getText());
//            pst.setString(2, usernameGetter);
//            pst.execute();
//            JOptionPane.showMessageDialog(this, "SUCCESSFULY UPDATED !", "WARNING", JOptionPane.INFORMATION_MESSAGE);
//            passwordGetter = txtConfirmNewPassword.getText();
//            Reset();
//            this.hide();
//            new Login().setVisible(true);
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(this, ex);
//        }
//    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (btnBack.getText().equals("BACK")) {
            this.hide();
            Reset();
            new Login().setVisible(true);
        } else {
            int P = JOptionPane.showConfirmDialog(null, " Are you sure want to cancel ?", "WARNING", JOptionPane.YES_NO_OPTION);
            if (P == JOptionPane.YES_OPTION) {
                this.hide();
                Reset();
                new Login().setVisible(true);
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
       
        try {
            String sql = "UPDATE tbl_user SET Password='"+txtConfirmNewPassword.getText()+"' WHERE Userid='"+txt_userid.getText()+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "SUCCESSFULY UPDATED !", "WARNING", JOptionPane.INFORMATION_MESSAGE);
            passwordGetter = txtConfirmNewPassword.getText();
            Reset();
            txt_userid.setText("");
            txt_secretcode.setText("");
            
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void txt_useridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_useridKeyReleased
        
        try {
            String sql = "SELECT * FROM tbl_user WHERE userid='"+txt_userid.getText()+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if (rs.next()) {
                txt_secretcode.setText(rs.getString("secret_answer"));
            }else{
                txt_secretcode.setText("");
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_txt_useridKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                 UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JCheckBox chckbox_ShowPassword1;
    private javax.swing.JCheckBox chckbox_ShowPassword2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConfirmNewPassword;
    private javax.swing.JLabel lblCurrentPassword;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JPasswordField txtConfirmNewPassword;
    private javax.swing.JPasswordField txtCurrentPassword;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txt_secretcode;
    private javax.swing.JTextField txt_userid;
    // End of variables declaration//GEN-END:variables
}
