/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author JayJomJohn
 */
public class CreateAccount extends javax.swing.JFrame {


    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    public CreateAccount() {
        initComponents();
        conn=JavaConnector.ConnectDb();
        
        SetIcon();
    }
//DISPLAY ICON
private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/IconA/icons8_airport_35px.png")));
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAnswer = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        chckbox_ShowSecretAnswer = new javax.swing.JCheckBox();
        cmbboxSecretQuestion = new javax.swing.JComboBox<>();
        lblPassword = new javax.swing.JLabel();
        lblSecretQuestion = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        showpassword = new javax.swing.JCheckBox();
        btnBack = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtSecretAnswer = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CREATE ACCOUNT");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CREATE ACCOUNT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAnswer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAnswer.setForeground(new java.awt.Color(255, 255, 255));
        lblAnswer.setText("Secret Answer:");
        jPanel2.add(lblAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 228, 132, 36));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("USERNAME:");
        jPanel2.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 36, 132, 36));

        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(211, 84, 0)));
        txtpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtpassword.setOpaque(false);
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordKeyTyped(evt);
            }
        });
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 84, 288, 36));

        chckbox_ShowSecretAnswer.setBackground(new java.awt.Color(51, 0, 102));
        chckbox_ShowSecretAnswer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chckbox_ShowSecretAnswer.setForeground(new java.awt.Color(255, 255, 255));
        chckbox_ShowSecretAnswer.setText("Show Secret Answer");
        chckbox_ShowSecretAnswer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chckbox_ShowSecretAnswer.setOpaque(false);
        chckbox_ShowSecretAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbox_ShowSecretAnswerActionPerformed(evt);
            }
        });
        jPanel2.add(chckbox_ShowSecretAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 276, 204, 36));

        cmbboxSecretQuestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbboxSecretQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "What is your favorite color?", "What is your contact number?", "When is your birthday?", "What is love for you?", "Where were you born ?", "What is the meaning of life?", "What is your gender?", "What is your civil status in life?", "What is your dream in life?", "What things that makes you happy?", "What things that makes you sad?", "What things that makes you mad?", "What is your job?", "What is your favorite song?", "What is your favorite band?", "What is your favorite singer?" }));
        jPanel2.add(cmbboxSecretQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 180, 288, 36));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("PASSWORD:");
        jPanel2.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 84, 132, 36));

        lblSecretQuestion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSecretQuestion.setForeground(new java.awt.Color(255, 255, 255));
        lblSecretQuestion.setText("Secret Question:");
        jPanel2.add(lblSecretQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 180, 132, 36));

        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(211, 84, 0)));
        txtusername.setCaretColor(new java.awt.Color(255, 255, 255));
        txtusername.setOpaque(false);
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtusernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 36, 288, 36));

        showpassword.setBackground(new java.awt.Color(51, 0, 102));
        showpassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showpassword.setForeground(new java.awt.Color(255, 255, 255));
        showpassword.setText("Show Password");
        showpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showpassword.setOpaque(false);
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(showpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 132, 204, 36));

        btnBack.setBackground(new java.awt.Color(211, 84, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconA/icons8_back_35px.png"))); // NOI18N
        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setIconTextGap(10);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 324, 180, 48));

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconA/icons8_save_35px.png"))); // NOI18N
        jButton2.setText("REGISTER");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setIconTextGap(10);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 324, 180, 48));

        txtSecretAnswer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSecretAnswer.setForeground(new java.awt.Color(255, 255, 255));
        txtSecretAnswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSecretAnswer.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(211, 84, 0)));
        txtSecretAnswer.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSecretAnswer.setOpaque(false);
        txtSecretAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSecretAnswerKeyTyped(evt);
            }
        });
        jPanel2.add(txtSecretAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 228, 288, 36));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 516, 444));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chckbox_ShowSecretAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbox_ShowSecretAnswerActionPerformed
        if (chckbox_ShowSecretAnswer.isSelected()) {
            txtSecretAnswer.setEchoChar((char) 0);
        } else {
            txtSecretAnswer.setEchoChar('*');
        }
        this.lblUsername.requestFocus();
    }//GEN-LAST:event_chckbox_ShowSecretAnswerActionPerformed

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        if (showpassword.isSelected()) {
            txtpassword.setEchoChar((char) 0);
        } else {
            txtpassword.setEchoChar('*');
        }
        this.lblUsername.requestFocus();
    }//GEN-LAST:event_showpasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
      if (txtusername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Username Found !", "ATTENTIOM", JOptionPane.ERROR_MESSAGE);
            txtusername.requestFocus();
        } else if (txtpassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Password Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtpassword.requestFocus();
        } else if (cmbboxSecretQuestion.getSelectedItem().equals("None")) {
            JOptionPane.showMessageDialog(this, "No Secret Question Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            cmbboxSecretQuestion.requestFocus();
        } else if (txtSecretAnswer.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Secret Answer Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtSecretAnswer.requestFocus();
        } else {
                        
            
        try {
            String sql = "INSERT INTO `tbl_user`(`Username`, `Password`, `Secret_Question`, `Secret_Answer`) "
                    + "VALUES (?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txtusername.getText());
            pst.setString(2,txtpassword.getText());
            pst.setString(3,cmbboxSecretQuestion.getSelectedItem().toString());
            pst.setString(4,txtSecretAnswer.getText());
            pst.execute();
            JOptionPane.showMessageDialog(this, "Registered Complete");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtusername.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_txtusernameKeyTyped

    private void txtusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyReleased
         if (!txtusername.getText().equals("")) {
            btnBack.setText("CANCEL");
        } else {
            btnBack.setText("BACK");
        }
    }//GEN-LAST:event_txtusernameKeyReleased

    private void txtpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtpassword.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_txtpasswordKeyTyped

    private void txtSecretAnswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSecretAnswerKeyTyped
         char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || Character.isWhitespace(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtSecretAnswer.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSecretAnswerKeyTyped

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (btnBack.getText().equals("BACK")) {
            this.hide();
            new Login().setVisible(true);
        } else {
            int P = JOptionPane.showConfirmDialog(null, " Are you sure want to cancel ?", "ATTENTION", JOptionPane.YES_NO_OPTION);
            if (P == JOptionPane.YES_OPTION) {
                this.hide();
                new Login().setVisible(true);
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                 UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JCheckBox chckbox_ShowSecretAnswer;
    private javax.swing.JComboBox<String> cmbboxSecretQuestion;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSecretQuestion;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JCheckBox showpassword;
    private javax.swing.JPasswordField txtSecretAnswer;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
